### ISSUE TITLE
Server failing heartbeat

### ISSUE THREAD

**Issue by DrDevinRX** [praydog/AutomataMP#4]
I'm trying to create my own server, but it's failing to send the heartbeat to the master server.
I have port 6969 forwarded for both TCP and UDP.

```
server -mode server
20:56:19.921 |  INFO | Server password: a
20:56:19.922 |  INFO | Created host
20:56:19.923 |  INFO | Sending heartbeat to master server
20:56:19.923 |  INFO | {"Name":"Galapagos","NumPlayers":0}
20:56:19.924 |  INFO | Sending heartbeat to https://niermaster.praydog.com/heartbeat
20:56:20.153 | ERROR | Error sending heartbeat: 400 Bad Request
```

Any help would be appreciated.

**Comment by praydog** [comment]
The current release build up must not be compatible with the master server, the master server is newer. 

You can get a newer build from here: https://github.com/praydog/AutomataMP/actions/runs/3027973861

I'll put up a newer build of the client/server.

**Comment by praydog** [comment]
Should be fixed in the newest release now.
